DatVeMayBay/Areas/Admin/Controllers/LoaiGheAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelPlain.EF;

namespace DatVeMayBay.Areas.Admin.Controllers
{
    public class LoaiGheAdminController : Controller
    {
        private DatVeMayBayDBEntities db = new DatVeMayBayDBEntities();

        // GET: Admin/LoaiGheAdmin
        public ActionResult Index()
        {
            ViewBag.loaighe = db.LOAIGHEs.ToList();
            return View();
        }

        // GET: Admin/LoaiGheAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIGHE lOAIGHE = db.LOAIGHEs.Find(id);
            if (lOAIGHE == null)
            {
                return HttpNotFound();
            }
            return View(lOAIGHE);
        }

        // GET: Admin/LoaiGheAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiGheAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MA_LOAIGHE,TEN_LOAIGHE,PHANTRAMGIA_LOAIGHE,TINHTRANG_LOAIGHE")] LOAIGHE lOAIGHE)
        {
            if (ModelState.IsValid)
            {
                db.LOAIGHEs.Add(lOAIGHE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lOAIGHE);
        }

        // GET: Admin/LoaiGheAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIGHE lOAIGHE = db.LOAIGHEs.Find(id);
            if (lOAIGHE == null)
            {
                return HttpNotFound();
            }
            return View(lOAIGHE);
        }

        // POST: Admin/LoaiGheAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MA_LOAIGHE,TEN_LOAIGHE,PHANTRAMGIA_LOAIGHE,TINHTRANG_LOAIGHE")] LOAIGHE lOAIGHE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lOAIGHE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lOAIGHE);
        }

        // GET: Admin/LoaiGheAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIGHE lOAIGHE = db.LOAIGHEs.Find(id);
            if (lOAIGHE == null)
            {
                return HttpNotFound();
            }
            return View(lOAIGHE);
        }

        // POST: Admin/LoaiGheAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LOAIGHE lOAIGHE = db.LOAIGHEs.Find(id);
            db.LOAIGHEs.Remove(lOAIGHE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DatVeMayBay/Areas/Admin/Views/LoaiGheAdmin/Create.cshtml
@model ModelPlain.EF.LOAIGHE

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-2">
    <div class="container-fluid">
        <div class="row">

            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Thêm Loại Ghế</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Create","LoaiGheAdmin",FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label>Tên Loại Ghế</label>
                            @Html.EditorFor(model => model.TEN_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TEN_LOAIGHE, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Phần tram giá</label>
                            @Html.EditorFor(model => model.PHANTRAMGIA_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIGHE, "", new { @class = "text-danger" })
                        </div>                        
                        <div class="form-check">
                            @Html.CheckBoxFor(model => model.TINHTRANG_LOAIGHE)
                            @Html.ValidationMessageFor(model => model.TINHTRANG_LOAIGHE, "", new { @class = "text-danger" })
                            <label class="form-check-label">Tình trạng</label>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Thêm</button>
                        @Html.ActionLink("Trở về", "Index")
                    </div>
                    }
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Danh Sách Loại Ghế</h3>

                        <div class="card-tools">
                            <ul class="pagination pagination-sm m-0 float-right">
                                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <table class="table">
                            <tr>
                                <th>Tên Quốc Gia</th>
                                <th>Tình trạng</th>
                                <th>Mở Rộng</th>
                            </tr>
                            @foreach (var item in quocgia)
                {
                    <tr>

                        <td>@Html.DisplayFor(modelItem => item.TEN_QUOCGIA)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TINHTRANG_QUOCGIA)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.MA_QUOCGIA }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.MA_QUOCGIA })
                        </td>
                    </tr>
    }
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
</section>

DatVeMayBay/Areas/Admin/Views/LoaiGheAdmin/Delete.cshtml
@model ModelPlain.EF.LOAIGHE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-danger">
                <div class="card-header">
                    <h3 class="card-title">Xoá chuyến bay</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Tên Loại Ghế:</label>
                        @Html.DisplayFor(model => model.TEN_LOAIGHE)
                    </div>
                    <div class="form-group">
                        <label>Phần Trăm:</label>
                        @Html.DisplayFor(model => model.PHANTRAMGIA_LOAIGHE)
                    </div>                                 
                </div>
                <div class="card-footer">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <input type="submit" value="Xoá" class="btn btn-danger" /> |
                            @Html.ActionLink("Về danh sách", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

DatVeMayBay/Areas/Admin/Views/LoaiGheAdmin/Edit.cshtml
@model ModelPlain.EF.LOAIGHE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-2">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Sửa Loại Ghế</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                          @Html.HiddenFor(model => model.MA_LOAIGHE)
                        <div class="card-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <label>Tên Loại Ghế</label>
                                @Html.EditorFor(model => model.TEN_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TEN_LOAIGHE, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Phần tram giá</label>
                                @Html.EditorFor(model => model.PHANTRAMGIA_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIGHE, "", new { @class = "text-danger" })
                            </div>                            
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-infor">Cập Nhật</button>
                            @Html.ActionLink("Trở về", "Index")
                        </div>
                    }
                </div>
            </div>
            </div>
        </div>
    </section>

DatVeMayBay/Areas/Admin/Views/LoaiGheAdmin/Index.cshtml
@model ModelPlain.EF.LOAIGHE

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var loaighe = (List<ModelPlain.EF.LOAIGHE>)ViewBag.loaighe;
}
<section class="content pt-2">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Thêm Loại Ghế</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Create", "LoaiGheAdmin", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="card-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <label>Tên Loại Ghế</label>
                                @Html.EditorFor(model => model.TEN_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TEN_LOAIGHE, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Phần trăm giá</label>
                                @Html.EditorFor(model => model.PHANTRAMGIA_LOAIGHE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIGHE, "", new { @class = "text-danger" })
                            </div>                            
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Thêm</button>
                            @Html.ActionLink("Trở về", "Index")
                        </div>
                    }
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Danh Sách Loại Ghế</h3>

                        <div class="card-tools">
                            <ul class="pagination pagination-sm m-0 float-right">
                                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <table class="table">
                            <tr>
                                <th>Tên Loại</th>
                                <th> Phân Trăm</th>
                                <th>Mở Rộng</th>
                            </tr>
                            @foreach (var item in loaighe)
                            {
                            <tr>

                                <td>@Html.DisplayFor(modelItem => item.TEN_LOAIGHE)</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PHANTRAMGIA_LOAIGHE)
                                </td>                               
                                <td>
                                    <a href="@Url.Action("Edit", "LoaiGheAdmin", new { id = item.MA_LOAIGHE })", class="pr-3">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>                                    
                                    <a href="@Url.Action("Delete", "LoaiGheAdmin", new { id = item.MA_LOAIGHE })">
                                        <i class="fa fa-times" aria-hidden="true" style="color:#d63031"></i>
                                    </a>
                                </td>                                
                            </tr>
                            }
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
</section>