DatVeMayBay/Areas/Admin/Controllers/MayBayAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelPlain.EF;

namespace DatVeMayBay.Areas.Admin.Controllers
{
    public class MayBayAdminController : Controller
    {
        private DatVeMayBayDBEntities db = new DatVeMayBayDBEntities();

        // GET: Admin/MayBayAdmin
        public ActionResult Index()
        {
            ViewBag.maybay = db.MAYBAYs.ToList();
            return View();
        }

        // GET: Admin/MayBayAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MAYBAY mAYBAY = db.MAYBAYs.Find(id);
            if (mAYBAY == null)
            {
                return HttpNotFound();
            }
            return View(mAYBAY);
        }

        // GET: Admin/MayBayAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/MayBayAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MA_MAYBAY,SOHIEU_MAYBAY,TINHTRANG_MAYBAY")] MAYBAY mAYBAY)
        {
            if (ModelState.IsValid)
            {
                db.MAYBAYs.Add(mAYBAY);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mAYBAY);
        }

        // GET: Admin/MayBayAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MAYBAY mAYBAY = db.MAYBAYs.Find(id);
            if (mAYBAY == null)
            {
                return HttpNotFound();
            }
            return View(mAYBAY);
        }

        // POST: Admin/MayBayAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MA_MAYBAY,SOHIEU_MAYBAY,TINHTRANG_MAYBAY")] MAYBAY mAYBAY)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mAYBAY).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mAYBAY);
        }

        // GET: Admin/MayBayAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MAYBAY mAYBAY = db.MAYBAYs.Find(id);
            if (mAYBAY == null)
            {
                return HttpNotFound();
            }
            return View(mAYBAY);
        }

        // POST: Admin/MayBayAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MAYBAY mAYBAY = db.MAYBAYs.Find(id);
            db.MAYBAYs.Remove(mAYBAY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DatVeMayBay/Areas/Admin/Views/MayBayAdmin/Delete.cshtml
@model ModelPlain.EF.MAYBAY

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row pt-2">
    <div class="col-md-6">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">Xoá Máy Bay</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->           
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Số hiệu máy bay:</label>
                            @Html.DisplayFor(model => model.SOHIEU_MAYBAY)
                        </div>
                        <div class="col-md-6">
                            @Html.CheckBoxFor(model => model.TINHTRANG_MAYBAY, new { htmlAttributes = new { @class = "minimal" } })
                            Tình trạng
                            @Html.ValidationMessageFor(model => model.SOHIEU_MAYBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>      
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    @using (Html.BeginForm())
    {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Xoá" class="btn btn-danger" /> |
                    @Html.ActionLink("Quay Lại", "Index")
                </div>
}
                </div>
        </div>
    </div>
</div>

DatVeMayBay/Areas/Admin/Views/MayBayAdmin/Edit.cshtml
@model ModelPlain.EF.MAYBAY

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row pt-2">
    <div class="col-md-6">
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">Sửa Máy Bay</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                 @Html.HiddenFor(model => model.MA_MAYBAY)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="card-body">
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.SOHIEU_MAYBAY, new { @class = "form-control", @placeholder = "Nhập Số Hiệu" })
                        @Html.ValidationMessageFor(model => model.SOHIEU_MAYBAY, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-check">
                        @Html.CheckBoxFor(model => model.TINHTRANG_MAYBAY, new { htmlAttributes = new { @class = "minimal" } })
                        Tình trạng
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <input type="submit" value="Sửa" class="btn btn-infor" />
                    @Html.ActionLink("Quay về", "Index")
                </div>
            }
        </div>
    </div>
 </div>
    

DatVeMayBay/Areas/Admin/Views/MayBayAdmin/Index.cshtml
@model ModelPlain.EF.MAYBAY

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var dsmaybay = (List<ModelPlain.EF.MAYBAY>)ViewBag.maybay;
}
<div class="row pt-2">
    <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Thêm Máy Bay</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            @using (Html.BeginForm("Create", "MayBayAdmin", FormMethod.Post, new { @role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="card-body">
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.SOHIEU_MAYBAY, new { @class = "form-control", @placeholder = "Nhập Số Hiệu" })
                        @Html.ValidationMessageFor(model => model.SOHIEU_MAYBAY, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-check">
                        @Html.CheckBoxFor(model => model.TINHTRANG_MAYBAY, htmlAttributes: new { @class = "minimal", @checked = true })
                        Tình trạng
                        @Html.ValidationMessageFor(model => model.SOHIEU_MAYBAY, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <input type="submit" value="Thêm" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh Sách Máy Bay</h3>

                <div class="card-tools">
                    <ul class="pagination pagination-sm m-0 float-right">
                        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                    <tr>
                        <th>Tên Quốc Gia</th>
                        <th>Tình trạng</th>
                        <th>Mở Rộng</th>
                    </tr>
                    @foreach (var item in dsmaybay)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.SOHIEU_MAYBAY)</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TINHTRANG_MAYBAY)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", "MayBayAdmin", new {  id = item.MA_MAYBAY })" , class="pr-3">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                                <a href="@Url.Action("Delete", "MayBayAdmin", new {  id = item.MA_MAYBAY   })">
                                    <i class="fa fa-times" aria-hidden="true" style="color:#d63031"></i>
                                </a>
                              
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>