DatVeMayBay/Areas/Admin/Controllers/LoaiKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelPlain.EF;

namespace DatVeMayBay.Areas.Admin.Controllers
{
    public class LoaiKhachHangController : Controller
    {
        private DatVeMayBayDBEntities db = new DatVeMayBayDBEntities();

        // GET: Admin/LoaiKhachHang
        public ActionResult Index()
        {
            ViewBag.loaikhachhang = db.LOAIKHACHes.ToList();
            return View();
        }

        // GET: Admin/LoaiKhachHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIKHACH lOAIKHACH = db.LOAIKHACHes.Find(id);
            if (lOAIKHACH == null)
            {
                return HttpNotFound();
            }
            return View(lOAIKHACH);
        }

        // GET: Admin/LoaiKhachHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiKhachHang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MA_LOAIKHACH,TEN_LOAIKHACH,PHANTRAMGIA_LOAIKHACH,TINHTRANG_LOAIKHACH")] LOAIKHACH lOAIKHACH)
        {
            if (ModelState.IsValid)
            {
                db.LOAIKHACHes.Add(lOAIKHACH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lOAIKHACH);
        }

        // GET: Admin/LoaiKhachHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIKHACH lOAIKHACH = db.LOAIKHACHes.Find(id);
            if (lOAIKHACH == null)
            {
                return HttpNotFound();
            }
            return View(lOAIKHACH);
        }

        // POST: Admin/LoaiKhachHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MA_LOAIKHACH,TEN_LOAIKHACH,PHANTRAMGIA_LOAIKHACH,TINHTRANG_LOAIKHACH")] LOAIKHACH lOAIKHACH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lOAIKHACH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lOAIKHACH);
        }

        // GET: Admin/LoaiKhachHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIKHACH lOAIKHACH = db.LOAIKHACHes.Find(id);
            if (lOAIKHACH == null)
            {
                return HttpNotFound();
            }
            return View(lOAIKHACH);
        }

        // POST: Admin/LoaiKhachHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LOAIKHACH lOAIKHACH = db.LOAIKHACHes.Find(id);
            db.LOAIKHACHes.Remove(lOAIKHACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DatVeMayBay/Areas/Admin/Views/LoaiKhachHang/Create.cshtml
@model ModelPlain.EF.LOAIKHACH

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LOAIKHACH</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TEN_LOAIKHACH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_LOAIKHACH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN_LOAIKHACH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PHANTRAMGIA_LOAIKHACH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PHANTRAMGIA_LOAIKHACH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIKHACH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TINHTRANG_LOAIKHACH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TINHTRANG_LOAIKHACH)
                    @Html.ValidationMessageFor(model => model.TINHTRANG_LOAIKHACH, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DatVeMayBay/Areas/Admin/Views/LoaiKhachHang/Delete.cshtml
@model ModelPlain.EF.LOAIKHACH

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-danger">
                <div class="card-header">
                    <h3 class="card-title">Xoá Loại Khách</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Tên Loại Khách:</label>
                        @Html.DisplayFor(model => model.TEN_LOAIKHACH)
                    </div>
                    <div class="form-group">
                        <label>Phần Trăm:</label>
                        @Html.DisplayFor(model => model.PHANTRAMGIA_LOAIKHACH)
                    </div>
                    <div class="form-group">
                        <label>Tình Trạng</label>
                        @Html.DisplayFor(model => model.TINHTRANG_LOAIKHACH)
                    </div>
                </div>
                <div class="card-footer">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <input type="submit" value="Xoá" class="btn btn-danger" /> |
                            @Html.ActionLink("Về danh sách", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

DatVeMayBay/Areas/Admin/Views/LoaiKhachHang/Details.cshtml
@model ModelPlain.EF.LOAIKHACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LOAIKHACH</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TEN_LOAIKHACH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_LOAIKHACH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PHANTRAMGIA_LOAIKHACH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHANTRAMGIA_LOAIKHACH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TINHTRANG_LOAIKHACH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TINHTRANG_LOAIKHACH)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MA_LOAIKHACH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DatVeMayBay/Areas/Admin/Views/LoaiKhachHang/Edit.cshtml
@model ModelPlain.EF.LOAIKHACH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-2">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Thêm Loại Ghế</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm())
                    {
                         @Html.AntiForgeryToken()
                         @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                         @Html.HiddenFor(model => model.MA_LOAIKHACH)
                        <div class="card-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <label>Tên Loại Khách Hàng</label>
                                @Html.EditorFor(model => model.TEN_LOAIKHACH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TEN_LOAIKHACH, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Phần tram giá</label>
                                @Html.EditorFor(model => model.PHANTRAMGIA_LOAIKHACH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIKHACH, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-check">
                                @Html.CheckBoxFor(model => model.TINHTRANG_LOAIKHACH)
                                @Html.ValidationMessageFor(model => model.TINHTRANG_LOAIKHACH, "", new { @class = "text-danger" })
                                <label class="form-check-label">Tình trạng</label>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Thêm</button>
                            @Html.ActionLink("Trở về", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

DatVeMayBay/Areas/Admin/Views/LoaiKhachHang/Index.cshtml
@model ModelPlain.EF.LOAIKHACH

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var loaikhachhang = (List<ModelPlain.EF.LOAIKHACH>)ViewBag.loaikhachhang;
}
<div class="row pt-2">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thêm Loại Khác</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            @using (Html.BeginForm("Create", "LoaiKhachHang", FormMethod.Post, new { @role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="card-body">
                <div class="form-group">
                    <label>Tên Loại Khách:</label>
                    @Html.TextBoxFor(model => model.TEN_LOAIKHACH, new { @class = "form-control", @placeholder = "Nhập Tên Loại Khác" })
                    @Html.ValidationMessageFor(model => model.TEN_LOAIKHACH, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label>Phần Trăm:</label>
                    @Html.TextBoxFor(model => model.PHANTRAMGIA_LOAIKHACH, new { @class = "form-control", @placeholder = "Phần Trăm" })
                    @Html.ValidationMessageFor(model => model.PHANTRAMGIA_LOAIKHACH, "", new { @class = "text-danger" })
                </div>
                <div class="form-check">
                    @Html.CheckBoxFor(model => model.TINHTRANG_LOAIKHACH, new { @class = "form-check-input", })
                    Tình Trạng Loại Khách
                    @Html.ValidationMessageFor(model => model.TINHTRANG_LOAIKHACH, "", new { @class = "text-danger" })
                </div>
            </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <input type="submit" value="Thêm" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách Loại Khách</h3>

                <div class="card-tools">
                    <ul class="pagination pagination-sm m-0 float-right">
                        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                    <tr>
                        <th>Tên Loại Khách Hàng</th>
                        <th>Phần trăm</th>
                        <th>Tình trạng</th>
                        <th>Mở Rộng</th>
                    </tr>
                    @foreach (var item in loaikhachhang)
                    {
                    <tr>

                        <td>@Html.DisplayFor(modelItem => item.TEN_LOAIKHACH)</td>
                        <td>@Html.DisplayFor(modelItem => item.PHANTRAMGIA_LOAIKHACH)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TINHTRANG_LOAIKHACH)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.MA_LOAIKHACH }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.MA_LOAIKHACH })
                        </td>
                    </tr>
                    }
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>