DatVeMayBay/Areas/Admin/Controllers/TuyenBayAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelPlain.EF;

namespace DatVeMayBay.Areas.Admin.Controllers
{
    public class TuyenBayAdminController : Controller
    {
        private DatVeMayBayDBEntities db = new DatVeMayBayDBEntities();

        // GET: Admin/TuyenBayAdmin
        public ActionResult Index()
        {
            var tUYENBAYs = db.TUYENBAYs.Include(t => t.SANBAY).Include(t => t.SANBAY1);
            return View(tUYENBAYs.ToList());
        }

        // GET: Admin/TuyenBayAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TUYENBAY tUYENBAY = db.TUYENBAYs.Find(id);
            if (tUYENBAY == null)
            {
                return HttpNotFound();
            }
            return View(tUYENBAY);
        }

    
        public ActionResult Create()
        {
            ViewBag.MA_SANBAY_DI = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY");
            ViewBag.MA_SANBAY_DEN = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY");
            return View();
        }
            
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TUYENBAY tUYENBAY, HttpPostedFileBase file)
        {

            var f = Request.Files["Upload"];
            if (f != null && f.ContentLength > 0 && ModelState.IsValid)
            {
                if(tUYENBAY.MA_SANBAY_DEN == tUYENBAY.MA_SANBAY_DI)
                {
                    ModelState.AddModelError("", "Không thể tạo điểm đến và điểm đi trùng nhau");
                    ViewBag.MA_SANBAY_DI = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DI);
                    ViewBag.MA_SANBAY_DEN = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DEN);
                    return View();
                }
                else
                {
                    var path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(f.FileName));
                    f.SaveAs(path);

                    tUYENBAY.HINHANH_TUYENBAY = "images/" + Path.GetFileName(f.FileName);
                    db.TUYENBAYs.Add(tUYENBAY);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }               

            }
            ViewBag.MA_SANBAY_DI = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DI);
            ViewBag.MA_SANBAY_DEN = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DEN);
            return View(tUYENBAY);
        }

        // GET: Admin/TuyenBayAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TUYENBAY tUYENBAY = db.TUYENBAYs.Find(id);
            if (tUYENBAY == null)
            {
                return HttpNotFound();
            }
            ViewBag.MA_SANBAY_DI = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DI);
            ViewBag.MA_SANBAY_DEN = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DEN);
            return View(tUYENBAY);
        }

        // POST: Admin/TuyenBayAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TUYENBAY tUYENBAY, HttpPostedFileBase file)
        {
            var f = Request.Files["Upload"];
            if (ModelState.IsValid)
            {
                if (f != null && f.ContentLength > 0)
                {
                    string filename = "~/Content/images/" + f.FileName;                   
                    var path = Path.Combine(Server.MapPath("~/Content/images/"), Path.GetFileName(f.FileName));
                    f.SaveAs(path);
                    tUYENBAY.HINHANH_TUYENBAY = "images/" + Path.GetFileName(f.FileName);                                    
                }
                db.Entry(tUYENBAY).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MA_SANBAY_DI = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DI);
            ViewBag.MA_SANBAY_DEN = new SelectList(db.SANBAYs, "MA_SANBAY", "TEN_SANBAY", tUYENBAY.MA_SANBAY_DEN);
            return View(tUYENBAY);
        }

        // GET: Admin/TuyenBayAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TUYENBAY tUYENBAY = db.TUYENBAYs.Find(id);
            if (tUYENBAY == null)
            {
                return HttpNotFound();
            }
            return View(tUYENBAY);
        }

        // POST: Admin/TuyenBayAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TUYENBAY tUYENBAY = db.TUYENBAYs.Find(id);
            db.TUYENBAYs.Remove(tUYENBAY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DatVeMayBay/Areas/Admin/Views/TuyenBayAdmin/Create.cshtml
@model ModelPlain.EF.TUYENBAY

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content pt-3">
    <div class="container-fluid">
        <!-- SELECT2 EXAMPLE -->
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">Thêm chuyến bay</h3>
            </div>
            @using (Html.BeginForm("Create", "TuyenBayAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

            <div class="card-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Tên Tuyến Bay</label>
                            @Html.EditorFor(model => model.TEN_TUYENBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TEN_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đi</label>
                            @Html.DropDownList("MA_SANBAY_DI", null, htmlAttributes: new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.MA_SANBAY_DI, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đến</label>
                            @Html.DropDownList("MA_SANBAY_DEN", null, htmlAttributes: new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.MA_SANBAY_DEN, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Giới Thiệu</label>
                            @Html.TextAreaFor(model => model.GIOITHIEU_TUYENBAY, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.GIOITHIEU_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Giá</label>
                            @Html.EditorFor(model => model.GIA_TUYENBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GIA_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Thời Gian Bay</label>
                            @Html.EditorFor(model => model.THOIGIANBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.THOIGIANBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="exampleInputFile">Hỉnh ảnh Tuyến</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    @Html.Editor("Upload", new { htmlAttributes = new { @class = "custom-file-input", @type = "file" } })

                                    <label class="custom-file-label" for="exampleInputFile">Chọn File</label>
                                    @Html.ValidationMessage("Upload", "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="card-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo" class="btn btn-primary" />
                            @Html.ActionLink("Quay Về", "Index")
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
@section Select2 {
    <!-- jQuery -->
    <script src="~/Content/admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Select2 -->
    <script src="~/Content/admin/plugins/select2/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="~/Content/admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap color picker -->
    <script src="~/Content/admin/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="~/Content/admin/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Content/admin/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="~/Content/admin/plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/admin/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/admin/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/admin/js/demo.js"></script>
    <!-- Page script -->
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()

            //Date range picker
            $('#reservation').daterangepicker()
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({
                timePicker: true,
                timePickerIncrement: 30,
                format: 'MM/DD/YYYY h:mm A'
            })
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                },
                function (start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            )

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            })
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass: 'iradio_minimal-red'
            })
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            })

            //Colorpicker
            $('.my-colorpicker1').colorpicker()
            //color picker with addon
            $('.my-colorpicker2').colorpicker()

            //Timepicker
            $('.timepicker').timepicker({
                showInputs: false
            })
        })
    </script>
}

DatVeMayBay/Areas/Admin/Views/TuyenBayAdmin/Delete.cshtml
@model ModelPlain.EF.TUYENBAY

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content pt-3">
    <div class="container-fluid">
        <!-- SELECT2 EXAMPLE -->
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">Xoá chuyến bay</h3>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Giới thiệu:</label>
                            @Html.DisplayFor(model => model.GIOITHIEU_TUYENBAY)
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Giá:</label>
                            @Html.DisplayFor(model => model.GIA_TUYENBAY)
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Thời Gian Bay:</label>
                            @Html.DisplayFor(model => model.THOIGIANBAY)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Tên Tuyến Bay:</label>
                            @Html.DisplayFor(model => model.TEN_TUYENBAY)
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đi:</label>
                            @Html.DisplayFor(model => model.SANBAY1.TEN_SANBAY)
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đến:</label>
                            @Html.DisplayFor(model => model.SANBAY.TEN_SANBAY)
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color">
                        <input type="submit" value="Xoá" class="btn btn-danger" /> |
                        @Html.ActionLink("Về danh sách", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</section>

DatVeMayBay/Areas/Admin/Views/TuyenBayAdmin/Edit.cshtml
@model ModelPlain.EF.TUYENBAY

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content pt-3">
    <div class="container-fluid">
        <!-- SELECT2 EXAMPLE -->
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">Sửa chuyến bay</h3>
            </div>
            @using (Html.BeginForm(Html.BeginForm("Edit", "TuyenBayAdmin", FormMethod.Post, new { enctype = "multipart/form-data" })))
            {
            <div class="card-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MA_TUYENBAY)
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Tên Tuyến Bay</label>
                            @Html.EditorFor(model => model.TEN_TUYENBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TEN_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đi</label>
                            @Html.DropDownList("MA_SANBAY_DI", null, htmlAttributes: new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.MA_SANBAY_DI, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Sân Bay Đến</label>
                            @Html.DropDownList("MA_SANBAY_DEN", null, htmlAttributes: new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.MA_SANBAY_DEN, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <img src="~/Content/@Html.DisplayFor(model=>model.HINHANH_TUYENBAY)" alt="" width="100%" />
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="exampleInputFile">Chọn ảnh khác</label>
                            <div class="input-group">
                                <div class="custom-file"> 
                                @Html.Editor("Upload", new { htmlAttributes = new { @class = "custom-file-input", @type = "file" } })

                                <label class="custom-file-label" for="">Chọn File</label>
                                @Html.ValidationMessage("Upload", "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Giới Thiệu</label>
                            @Html.TextAreaFor(model => model.GIOITHIEU_TUYENBAY, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.GIOITHIEU_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Giá</label>
                            @Html.EditorFor(model => model.GIA_TUYENBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GIA_TUYENBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group">
                            <label>Thời Gian</label>
                            @Html.EditorFor(model => model.THOIGIANBAY, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.THOIGIANBAY, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-info" />
                            @Html.ActionLink("Quay Về", "Index")
                        </div>
                    </div>
                </div>
              </div>
             }
            </div>
    </div>
</section>
@section Select2 {
    <!-- jQuery -->
    <script src="~/Content/admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Select2 -->
    <script src="~/Content/admin/plugins/select2/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="~/Content/admin/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="~/Content/admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap color picker -->
    <script src="~/Content/admin/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="~/Content/admin/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Content/admin/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="~/Content/admin/plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/admin/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/admin/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/admin/js/demo.js"></script>
    <!-- Page script -->
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()

            //Date range picker
            $('#reservation').daterangepicker()
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({
                timePicker: true,
                timePickerIncrement: 30,
                format: 'MM/DD/YYYY h:mm A'
            })
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                },
                function (start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            )

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            })
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass: 'iradio_minimal-red'
            })
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            })

            //Colorpicker
            $('.my-colorpicker1').colorpicker()
            //color picker with addon
            $('.my-colorpicker2').colorpicker()

            //Timepicker
            $('.timepicker').timepicker({
                showInputs: false
            })
        })
    </script>
}

DatVeMayBay/Areas/Admin/Views/TuyenBayAdmin/Index.cshtml
@model IEnumerable<ModelPlain.EF.TUYENBAY>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<section class="content pt-2">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Danh Sách Chuyến Bay</h3>
                    <div class="card-tools">
                        <a href="@Url.Action("Create", "TuyenBayAdmin")" class=" btn btn-success">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        </a>
                      
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>                                
                                <th>Tên chuyến Bay</th>
                                <th>Hình tuyến</th>
                                <th>Giá</th>
                                <th>Thời Gian</th>
                                <th>Tên Sân Bay Đi</th>
                                <th>Tên Sân Bay Đến</th>
                                <th>Tiện Ích</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TEN_TUYENBAY)
                                    </td>
                                    <td>
                                        <img src="~/Content/@Html.DisplayFor(modelItem => item.HINHANH_TUYENBAY)"  alt="" height="100px" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GIA_TUYENBAY)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.THOIGIANBAY)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SANBAY.TEN_SANBAY)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SANBAY1.TEN_SANBAY)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "TuyenBayAdmin", new { id = item.MA_TUYENBAY})" , class="pr-3">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </a>
                                        <a href="@Url.Action("Delete", "TuyenBayAdmin", new {id = item.MA_TUYENBAY })">
                                            <i class="fa fa-times" aria-hidden="true" style="color:#d63031"></i>
                                        </a>                                      
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
</section>
@section DataTables{
    <!-- DataTables -->
    <script src="~/Content/admin/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/admin/plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Content/admin/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/admin/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/admin/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/admin/js/demo.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
    </script>
}